// <auto-generated />
using DnDExamBL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DnDExamBL.Migrations
{
    [DbContext(typeof(DndDbContext))]
    [Migration("20240109073200_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DnDExamModels.EnemyModel", b =>
                {
                    b.Property<int>("EnemyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnemyId"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("EnemyId");

                    b.ToTable("Enemies", (string)null);

                    b.HasData(
                        new
                        {
                            EnemyId = 1,
                            ArmorClass = 15,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = "3d6",
                            DamageModifier = 2,
                            HitPoints = 40,
                            Name = "Warlock"
                        },
                        new
                        {
                            EnemyId = 2,
                            ArmorClass = 12,
                            AttackModifier = 1,
                            AttackPerRound = 2,
                            Damage = "1d4",
                            DamageModifier = 0,
                            HitPoints = 25,
                            Name = "Goblin"
                        },
                        new
                        {
                            EnemyId = 3,
                            ArmorClass = 18,
                            AttackModifier = 3,
                            AttackPerRound = 5,
                            Damage = "4d8",
                            DamageModifier = 3,
                            HitPoints = 80,
                            Name = "Dragon"
                        },
                        new
                        {
                            EnemyId = 4,
                            ArmorClass = 14,
                            AttackModifier = -2,
                            AttackPerRound = 2,
                            Damage = "3d4",
                            DamageModifier = 1,
                            HitPoints = 35,
                            Name = "Orc"
                        },
                        new
                        {
                            EnemyId = 5,
                            ArmorClass = 10,
                            AttackModifier = 0,
                            AttackPerRound = 1,
                            Damage = "1d8",
                            DamageModifier = 0,
                            HitPoints = 15,
                            Name = "Skeleton"
                        },
                        new
                        {
                            EnemyId = 6,
                            ArmorClass = 16,
                            AttackModifier = 4,
                            AttackPerRound = 2,
                            Damage = "2d8",
                            DamageModifier = 3,
                            HitPoints = 50,
                            Name = "Troll"
                        },
                        new
                        {
                            EnemyId = 7,
                            ArmorClass = 13,
                            AttackModifier = 1,
                            AttackPerRound = 1,
                            Damage = "3d4",
                            DamageModifier = -2,
                            HitPoints = 30,
                            Name = "Wraith"
                        },
                        new
                        {
                            EnemyId = 8,
                            ArmorClass = 11,
                            AttackModifier = -1,
                            AttackPerRound = 2,
                            Damage = "1d10",
                            DamageModifier = 0,
                            HitPoints = 20,
                            Name = "Harpy"
                        },
                        new
                        {
                            EnemyId = 9,
                            ArmorClass = 17,
                            AttackModifier = 3,
                            AttackPerRound = 3,
                            Damage = "4d4",
                            DamageModifier = 2,
                            HitPoints = 60,
                            Name = "Beholder"
                        },
                        new
                        {
                            EnemyId = 10,
                            ArmorClass = 19,
                            AttackModifier = -2,
                            AttackPerRound = 4,
                            Damage = "5d6",
                            DamageModifier = 3,
                            HitPoints = 70,
                            Name = "Lich"
                        },
                        new
                        {
                            EnemyId = 11,
                            ArmorClass = 15,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = "1d12",
                            DamageModifier = -1,
                            HitPoints = 45,
                            Name = "Minotaur"
                        },
                        new
                        {
                            EnemyId = 12,
                            ArmorClass = 16,
                            AttackModifier = -1,
                            AttackPerRound = 1,
                            Damage = "1d10",
                            DamageModifier = 0,
                            HitPoints = 55,
                            Name = "Gorgon"
                        },
                        new
                        {
                            EnemyId = 13,
                            ArmorClass = 18,
                            AttackModifier = 2,
                            AttackPerRound = 2,
                            Damage = "2d6",
                            DamageModifier = 1,
                            HitPoints = 65,
                            Name = "Sphinx"
                        },
                        new
                        {
                            EnemyId = 14,
                            ArmorClass = 12,
                            AttackModifier = 2,
                            AttackPerRound = 1,
                            Damage = "1d4",
                            DamageModifier = 0,
                            HitPoints = 25,
                            Name = "Banshee"
                        },
                        new
                        {
                            EnemyId = 15,
                            ArmorClass = 20,
                            AttackModifier = 3,
                            AttackPerRound = 3,
                            Damage = "2d6",
                            DamageModifier = 1,
                            HitPoints = 75,
                            Name = "Chimera"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
